### ISSUE TITLE
config-translator helper now writes to stderr

### ISSUE THREAD

**Issue by corbesero** [gp42/aws_cloudwatch#12]
It appears that aws has released an update of the cloudwatch rpms.
In the update, the config-translator now writes things to stderr that previously went to stdout, and the grep fails in your resource to look for a successful run.

This command is executed.

`/opt/aws/amazon-cloudwatch-agent/bin/config-translator --input /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json --output /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.toml --mode auto --config /opt/aws/amazon-cloudwatch-agent/etc/common-config.toml)`

and this is the output
`2022/05/12 16:11:28 D! [EC2] Found active network interface
I! Detected the instance is EC2
2022/05/12 16:11:28 Reading json config file path: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json ...
Cannot access : lstat : no such file or directory2022/05/12 16:11:28 unable to scan config dir with error: lstat : no such file or directory
2022/05/12 16:11:28 I! Valid Json input schema.
I! Detecting run_as_user...
No csm configuration found.
No log configuration found.
Configuration validation first phase succeeded`

but the **Valid Json input schema** is not going to stdout.

I ran those commands as route to get the output.

**Comment by sureshc** [comment]
We’re running into this issue as well. Any suggested workarounds?

**Comment by azaharenko-sloboda-studio** [comment]
I have the same issue. Any ideas or updates?

**Comment by gp42** [comment]
I was able to reproduce, will work on a fix. Thank you for submission!

**Comment by gp42** [comment]
This is resolved with v2.0.0
