### ISSUE TITLE
Ubuntu 18.04

### ISSUE THREAD

**Issue by guywilkins** [gp42/aws_cloudwatch#6]
Is there any plan to make this compatible with Ubuntu 18.04?

**Comment by gp42** [comment]
Just checked [`AWS`](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Install-CloudWatch-Agent.html), and i can see that they started supporting Ubuntu 18.04.
Will add support within a couple of days.

See branch: https://github.com/gp42/aws_cloudwatch/tree/i6_ubuntu18
